package com.example.software_eng_asoee_2024;/* DONE  */
public class PharmacudicalProduct {
    private String name;
    private Integer retailPrice; // in cents
    private Form form;
    private MedicineType type;


    public PharmacudicalProduct() {
    }

    public PharmacudicalProduct(String name, Integer retailPrice, Form form, MedicineType type) {
        this.name = name;
        this.retailPrice = retailPrice;
        this.form = form;
        this.type = type;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getRetailPrice() {
        return this.retailPrice;
    }

    public void setRetailPrice(Integer retailPrice) {
        this.retailPrice = retailPrice;
    }

    public Form getForm() {
        return this.form;
    }

    public void setForm(Form form) {
        this.form = form;
    }

    public MedicineType getMedicineType() {
        return this.type;
    }

    public void setMedicineType(MedicineType type) {
        this.type = type;
    }

    /* Getters generated by combining field values */
    public Integer getCustomerParticipation(){
        Integer participation;
        if ( getMedicineType() == MedicineType.GENERIC){
            participation = 10;
        }
        else{
            // GENERIC
            participation = 2;
        }
        return participation;
    }

    public Integer getFinalPrice(){
        // TODO might need to change this because of truncation errors, not sure...
        return (getRetailPrice() * getCustomerParticipation()) / 100;
    }
}
