public class PharmacudicalProduct {
    private String name;
    private Integer retailPrice; // in cents
    private Form form;
    private MedicineType type;

    public PharmacudicalProduct() {
    }

    public PharmacudicalProduct(String name, Integer retailPrice, Form form, MedicineType type) {
        this.name = name;
        this.retailPrice = retailPrice;
        this.form = form;
        this.type = type;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getRetailPrice() {
        return this.retailPrice;
    }

    public void setRetailPrice(Integer retailPrice) {
        this.retailPrice = retailPrice;
    }

    public Form getForm() {
        return this.form;
    }

    public void setForm(Form form) {
        this.form = form;
    }

    public MedicineType getMedicineType() {
        return this.type;
    }

    public void setMedicineType(MedicineType type) {
        this.type = type;
    }

    /* Getters generated by combining field values */
    public Float getCustomerParticipation() {
        Float participation;
        if (getMedicineType() == MedicineType.GENERIC) {
            participation = 0.1f;
        } else {
            // GENERIC
            participation = 0.02f;
        }
        return participation;
    }

    public Integer getFinalPrice() {
        return Math.round(getRetailPrice() * getCustomerParticipation());
    }
}
